views/staff/__init__.py
from flask import Blueprint

staff_blu = Blueprint("staff",__name__)
from . import views

views/staff/views.py
import base64
import os
import config
from flask import current_app, redirect, render_template, request, session, url_for, flash,g
import re
import mysql
import mysql.connector
from . import staff_blu


# connect database
def getCursor():
    global dbconn
    global connection
    connection = mysql.connector.connect(user=config.dbuser, \
    password=config.dbpass, host=config.dbhost, \
    database=config.dbname, autocommit=True,auth_plugin='mysql_native_password')
    dbconn = connection.cursor()
    return dbconn

# upload images format setting
ALLOWED_EXTENSIONS = {'png', 'jpg', 'jpeg', 'gif'}

# check the format of the file is an image
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS

# get forestry data
def forestry_get(forestry_id):
    global detail_list,image_list
    connection = getCursor()
    connection.execute("""SELECT f.forestry_id,f.forestry_type,
                        case when f.present_in_nz = 1 then "yes" when f.present_in_nz=0 then "no" ELSE 'null' END
                        ,f.common_name,f.scientific_name,f.key_charac,f.biology,f.symptoms,i.images
                        FROM forestry f left join images i
                        on f.forestry_id = i.forestry_id
                        where i.show_p = 1 and f.forestry_id = %s""",(forestry_id,))
    detail_list = connection.fetchall()

    # select all images of the forestry
    connection.execute("""SELECT image_num,forestry_id,images FROM images where forestry_id = %s and show_p=0;""",(forestry_id,))
    image_list= connection.fetchall()

    
@staff_blu.route("/index",methods = ["GET","POST"])
def s_index():
    if session['userid'] and session['role'] == "staff" and session['status']== 1:
        connection = getCursor()
        # page setting
        page = request.args.get("page",1,type=int) 
        per_page = 10
        offset = (page -1) * per_page
        connection.execute("""SELECT f.forestry_id,f.forestry_type,
            case when f.present_in_nz = 1 then "yes" when f.present_in_nz=0 then "no" ELSE 'null' END
            ,f.common_name,i.images
            FROM forestry f left join images i
            on f.forestry_id = i.forestry_id
            where i.show_p = 1 order by f.forestry_id limit %s offset %s""",(per_page,offset,))
        guide_list = connection.fetchall()     

        connection.execute("select count(*) from forestry;")
        total = connection.fetchone()[0]   
        total_pages = total // per_page + (1 if total % per_page > 0 else 0)  # calculate the total pages

        if request.method == 'GET':    
            return render_template("staff/guide.html",guide_list=guide_list,page=page,total_pages=total_pages)
        else:
            # delete guide
            if request.values.get("del_guide") == "del_guide":
                forid= request.form.get("delid")
                connection.execute("delete from forestry where forestry_id=%s",(forid,))  
                flash("Delete successfully!","success")
            
            # upload images
            elif request.values.get("upload") == "upload":
                forid= int(request.form.get("forid"))
                if 'fileimg' not in request.files:
                    flash("No file part. Fail to add the image","danger")
                    return redirect(url_for('staff.s_index'))
                file_img = request.files.get("fileimg")
                if file_img.filename == '':
                    flash("No selected file. Fail to add the image","danger")
                    return redirect(url_for('staff.s_index'))
                if "fileimg" in request.files and allowed_file(file_img.filename):
                    file_img = request.files.get("fileimg")
                    file_name = file_img.filename
                    file_path = "/Users/doubleluo/Documents/GitHub/Biosecurity/static/imgdata/" + file_name
                    file_img.save(file_path)
                    connection.execute("select images from images where forestry_id=%s",(forid,))
                    images = connection.fetchall() 
                    if images[0][0]!=None:   # the forestry already have images
                        connection.execute("insert into images (forestry_id,images) values (%s,%s)", (forid,file_name,))
                    else:
                        connection.execute("update images set images=%s where forestry_id=%s", (file_name,forid,))
                    flash("File saved successfully","success")
                else:
                    flash('Invalid file type. Only PNG, JPG, JPEG, and GIF files are allowed.', 'danger')

            return redirect(url_for('staff.s_index'))
    else:
        return redirect(url_for('login'))


@staff_blu.route("/guide",methods = ["GET","POST"])
def s_guide():
        if session['userid'] and session['role'] == "staff" and session['status']== 1:
            connection = getCursor()
            # add guide
            if request.values.get("add") == "add":
                typ = request.form.get('group1')
                present = request.form.get("group2")
                common= request.form.get("common")
                scientific= request.form.get("sci")
                keys= request.form.get("key").strip()
                bio= request.form.get("biology").strip()
                symptoms= request.form.get("symptoms").strip()

                connection.execute("""insert into forestry  
                    (forestry_type,present_in_nz,common_name,scientific_name,key_charac, biology, symptoms) values
                    (%s,%s,%s,%s,%s,%s,%s)""",(typ,present,common,scientific,keys,bio,symptoms,))  
                
                connection.execute("select max(forestry_id) from forestry")
                forid = connection.fetchone()[0]
   
                flash("Add Forestry ID:{} successfully!".format(forid),"success")

                # upload images
                if 'fileimg' not in request.files:
                    connection.execute("""insert into images 
                        (forestry_id,show_p) values
                        (%s,%s)""",(forid,1))  
                    return render_template("staff/add_guide.html")
                file_img = request.files.get("fileimg")

                if file_img.filename == '':
                    connection.execute("""insert into images(forestry_id,show_p) values(%s,%s)""",(forid,1))  
                    return render_template("staff/add_guide.html")
                if "fileimg" in request.files and allowed_file(file_img.filename):
                    file_img = request.files.get("fileimg")
                    file_name = file_img.filename
                    file_path = "/Users/doubleluo/Documents/GitHub/Biosecurity/static/imgdata/" + file_name
                    file_img.save(file_path)
                    connection.execute("insert into images (forestry_id,images,show_p) values (%s,%s,1)", (forid,file_name,))
                else:
                    flash('But fail to add the file. Invalid file type. Only PNG, JPG, JPEG, and GIF files are allowed.', 'danger')
                    connection.execute("""insert into images(forestry_id,show_p) values(%s,%s)""",(forid,1))  
            
            return render_template("staff/add_guide.html")


@staff_blu.route("/detail",methods = ["GET","POST"])
def s_detail():   
    connection = getCursor()
    if session['userid'] and session['role'] == "staff" and session['status']== 1:
        forestry_id = request.args.get('forestry_id')   
        # forestry_get(forestry_id)
        if request.method == 'GET':                   
            forestry_get(forestry_id)
            return render_template("/staff/detail.html",detail_list=detail_list,image_list=image_list)    
        else:  
            # edit the detail 
            if request.values.get("edit") == "edit":
                forid= request.form.get("idnum") 
                common= request.form.get("common")
                scientific= request.form.get("scientific").strip()
                key= request.form.get("key").strip()
                bio= request.form.get("biology").strip()
                symptoms= request.form.get("symptoms").strip()
                type = request.form.get('group1')
                present = request.form.get("group2")
                connection.execute("""update forestry set 
                    forestry_type=%s,present_in_nz=%s,common_name=%s,scientific_name=%s,
                    key_charac=%s, biology=%s, symptoms=%s where forestry_id=%s""",(type,present,common,scientific,key,bio,symptoms,forid,))  
                flash("Update successfully!","success")

            # change picture
            elif request.values.get("save") == "save":
                img = request.form.get("img1")
                forid = request.form.get("forestry1")
                connection.execute("update images set show_p=0 where forestry_id=%s",(forid,))
                connection.execute("update images set show_p=1 where image_num=%s",(img,))
                flash("Change primary picture successfully!","success")

            # delete picture
            elif request.values.get("delimg") == "delimg":
                img = request.form.get("img")
                forid = request.form.get("forestry")
                connection.execute("delete from images where image_num=%s",(img,))
                flash("Delete picture successfully!","success")

            # get the data from database again after all change
            forestry_get(forid)
            return render_template("/staff/detail.html",detail_list=detail_list,image_list=image_list)          
    else:
        return redirect(url_for('login'))
      

@staff_blu.route("/profile",methods = ["GET","POST"])
def s_profile():
    hashing = g.hashing
    connection = getCursor()
    if session['userid'] and session['role'] == "staff" and session['status']== 1:
        # get the profile from database

templates/staff/add_guide.html
{% extends "staff/s_base.html" %}

{% block title %}{{Guide}}{% endblock %}

{% block content %}

<div class="container">
  <div class="row justify-content-md-center">
  <div style="text-align: center">
    <h5>Add Guide</h5>
  </div>
  <form class="form-horizontal needs-validation" style="margin-top: 40px;" action="/staff/guide" method="POST" id="add_myForm" enctype="multipart/form-data">
    <div class="row">
      <div class="col-md-2">
        <div><label for="message-text" class="col-form-label">Forestry type</label></div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="group1" value="pest" checked>
          <label class="form-check-label" for="group1">pest</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="group1" value="disease">
          <label class="form-check-label" for="group1">disease</label>
        </div>
      </div>
      <div class="col-md-2">
        <div><label for="message-text" class="col-form-label">Present in NZ</label></div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="group2" value=1 checked>
          <label class="form-check-label" for="group2">yes</label>
        </div>
        <div class="form-check form-check-inline">
          <input class="form-check-input" type="radio" name="group2" value=0>
          <label class="form-check-label" for="group2">no</label>
        </div>
      </div>
      <div class="col-md-4">
        <label for="message-text" class="col-form-label">Common name</label>
        <input type="text" class="form-control" name="common" id="common" required>
      </div>
      <div class="col-md-4">
        <label for="message-text" class="col-form-label">Scientific name</label>
        <input type="text" class="form-control" name="sci" id="sci" required>
      </div>
    </div>
    
    <div class="row">
      <label for="message-text" class="col-form-label">Key character</label>
      <textarea class="form-control" name="key" id="key"></textarea>
    </div>
    <div class="row">
      <label for="biology" class="col-form-label">Biology/Description</label>
      <textarea class="form-control" name="biology" id="biology"></textarea>
    </div>
    <div class="row">
      <label for="symptoms" class="col-form-label">Symptoms</label>
      <textarea class="form-control" name="symptoms" id="symptoms"></textarea>
    </div>

    <!-- add image -->
   <div class="row">
    <div class="col-md-6">
    <label for="symptoms" class="col-form-label">Upload image</label>
      <div class="mb-3">
        <input type="file" class="form-control" name="fileimg" id="fileimg">
      </div>
    </div>
   </div>

    <div class="form-check" style="padding:35px 25px">
      <input type="checkbox" class="form-check-input" id="inlineFormCheck" required>
      <label class="form-check-label" for="inlineFormCheck">Check me out</label>
    </div>
    <div style="text-align: center; padding:10px">
        <button type="submit" class="btn btn-primary" name="add" value="add">Submit</button>
    </div>
  </div>

  </form>
</div>
</div>


<script>
  // get the radio
  const radioButtonsGroup1 = document.querySelectorAll('input[name="group1"]');  // type
  const radioButtonsGroup2 = document.querySelectorAll('input[name="group2"]');  // present in nz
  
  radioButtonsGroup1.forEach(function(radioButton) {
    radioButton.addEventListener('change', function(event) {
      // get the value of the radiao
      const selectedValue = document.querySelector('input[name="group1"]:checked').value;
      console.log('Selected value of group 1:', selectedValue);
    });
  });

  radioButtonsGroup2.forEach(function(radioButton) {
    radioButton.addEventListener('change', function(event) {
      // get the value of the radio
      const selectedValue = document.querySelector('input[name="group2"]:checked').value;
      console.log('Selected value of group 2:', selectedValue);
    });
  });

</script>
{% endblock %}

templates/staff/detail.html
{% extends "staff/s_base.html" %}

{% block title %}{{Detail}}{% endblock %}

{% block header %}{% endblock %}

{% block content %}
{% for detail in detail_list %}
<div style="text-align:center">
  <button type="button" class="btn btn-primary" onclick="Values('{{ detail[0] }}','{{ detail[3]|urlencode }}','{{ detail[4]|urlencode }}','{{ detail[5]|urlencode }}','{{ detail[6]|urlencode }}','{{ detail[7]|urlencode }}')" data-bs-toggle="modal" data-bs-target="#exampleModal{{ detail[0] }}">Edit the content</button>
</div>
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Type</th>
        <th scope="col">Present in NZ</th>
        <th scope="col">Common Name</th>
        <th scope="col">Scientific name</th>
        <th scope="col">Primary Image</th>
        <th scope="col">Click to edit the images ⬇️</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <th>{{detail[0]}}</th>
        <td>{{detail[1]}}</td>
        <td>{{detail[2]}}</td>
        <td>{{detail[3]}}</td>
        <td>{{detail[4]}}</td>
        <td>
          <img class="img-rounded" src="../static/imgdata/{{detail[8]}}" width=auto height="200px">
        </td>
        <td>
          <div style="height:50px">
            <div class="h-50 d-inline-block" style="width: 200px;">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner ">
                {% for images in image_list %}
                <div class="carousel-item active">
                  <img class="mx-auto d-block" width=auto height="200px" onclick="Valuesimg('{{ images[0] }}','{{ images[1] }}','{{ images[0] }}','{{ images[1] }}')"  src="../static/imgdata/{{ images[2] }}" data-bs-toggle="modal" data-bs-target="#imgmodal{{ detail[0] }}">
                </div>
                {% endfor %}
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          </div>
          </div>
        </td>
      </tr>
     
    </tbody> 
  </table>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Key characteristics</th>
        <th scope="col">Biology/Description</th>
        <th scope="col">Symptoms</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>{{detail[5]}}</td>
        <td>{{detail[6]}}</td>
        <td>{{detail[7]}}</td>
      </tr>   
    </tbody>
  </table>

<!-- Modal edit-->
<div class="modal fade" id="exampleModal{{ detail[0] }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Detail</h5>
      </div>
      <div class="modal-body">
        <div class="container-fluid">
          <form class="form-horizontal" style="margin-top: 40px;" action="/staff/detail" method="POST" id="myForm">
            <div class="col-md-6 mb-3">
              <label for="idnum" class="col-form-label">ID</label>
              <input type="text" class="form-control" name="idnum" id="idnum" readonly>
            </div>
          <div class="row">
          <div class="col-md-6 mb-3">
            <label for="group1" class="col-form-label">Type: </label>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="group1" value="pest" {% if detail[1] == 'pest' %} checked {% endif %}>
              <label class="form-check-label" for="group1">Pest</label>            
            </div>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="group1" value="disease" {% if detail[1] == 'disease' %} checked {% endif %}>
              <label class="form-check-label" for="group1">Disease</label>
            </div>
          </div>   
          <div class="col-md-6 mb-3">
            <label for="group2" class="col-form-label">Present in NZ: </label>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="group2" value="1" {% if detail[2] == 'yes' %} checked {% endif %}>
              <label class="form-check-label" for="group2">Yes</label>            
            </div>
            <div class="form-check form-check-inline">
              <input class="form-check-input" type="radio" name="group2" value="0" {% if detail[2] == 'no' %} checked {% endif %}>
              <label class="form-check-label" for="group2">No</label>
            </div>
          </div>
         </div>
         <div class="row">
          <div class="col-md-6 mb-3">
            <label for="common" class="col-form-label">Common Name</label>
            <input type="text" class="form-control" name="common" id="common">
          </div>
          <div class="col-md-6 mb-3">
            <label for="scientific" class="col-form-label">Scientific Name</label>
            <input type="text" class="form-control" name="scientific" id="scientific">
          </div>
         </div>
          <div class="mb-3 text-truncate">
            <label for="key" class="col-form-label">Key characteristics</label>
            <textarea class="form-control" name="key" id="key"></textarea>
          </div>
          <div class="mb-3 text-truncate">
            <label for="biology" class="col-form-label">Biology/Description</label>
            <textarea class="form-control" name="biology" id="biology"></textarea>
          </div>
          <div class="mb-3 text-truncate">
            <label for="symptoms" class="col-form-label">Symptoms</label>
            <textarea class="form-control" name="symptoms" id="symptoms"></textarea>
          </div>
        </form>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" form="myForm" name="edit" value="edit">Save changes</button>
      </div>
    </div>
  </div>
</div>

<!-- Modal image change-->
<div class="modal fade" id="imgmodal{{ detail[0] }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit Images</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Do you want to Save this image as the primary image or Delete this image?
      </div>
      <form class="form-horizontal" style="margin-top: 40px;" action="/staff/detail" method="POST" id="myForm2">
        <input type="hidden" class="form-control" name="img" id="img">
        <input type="hidden" class="form-control" name="forestry" id="forestry">
      </form>
      <form class="form-horizontal" style="margin-top: 40px;" action="/staff/detail" method="POST" id="myForm3">
        <input type="hidden" class="form-control" name="img1" id="img1">
        <input type="hidden" class="form-control" name="forestry1" id="forestry1">
      </form>
      <div class="modal-footer">
        <button type="submit" class="btn btn-danger" form="myForm2" name="delimg" value="delimg">Delete</button>
        <button type="submit" class="btn btn-primary"form="myForm3" name="save" value="save">Save as Primary Image</button>
      </div>
    </div>
  </div>
</div> 

{% endfor %}

<script>
  // get the radio
  const radioButtonsGroup1 = document.querySelectorAll('input[name="group1"]');  // type
  const radioButtonsGroup2 = document.querySelectorAll('input[name="group2"]');  // present in nz
  
  radioButtonsGroup1.forEach(function(radioButton) {
    radioButton.addEventListener('change', function(event) {
      // get the value of the radio
      const selectedValue = document.querySelector('input[name="group1"]:checked').value;
      console.log('Selected value of group 1:', selectedValue);
    });
  });

  radioButtonsGroup2.forEach(function(radioButton) {
    radioButton.addEventListener('change', function(event) {
      // get the value of the radio
      const selectedValue = document.querySelector('input[name="group2"]:checked').value;
      console.log('Selected value of group 2:', selectedValue);
    });
  });


  // get the info when edit
  function Values(idnum,common, scientific, key, biology, symptoms) {
    common = decodeURIComponent(common);
    scientific = decodeURIComponent(scientific);
    key = decodeURIComponent(key);
    biology = decodeURIComponent(biology);
    symptoms = decodeURIComponent(symptoms);

    document.getElementById("idnum").value = idnum;
    document.getElementById("common").value = common;
    document.getElementById("scientific").value = scientific;
    document.getElementById("key").value = key;
    document.getElementById("biology").value = biology;
    document.getElementById("symptoms").value = symptoms;
}

// get the info when edit images
function Valuesimg(img,forestry,img1,forestry1) {
    document.getElementById("img").value = img;
    document.getElementById("forestry").value = forestry;
    document.getElementById("img1").value = img1;
    document.getElementById("forestry1").value = forestry1;
}

</script>


{% endblock %}

templates/staff/guide.html
{% extends "staff/s_base.html" %}

{% block title %}{{Guide}}{% endblock %}

{% block content %}

<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Type</th>
        <th scope="col">Present in NZ</th>
        <th scope="col">Common Name</th>
        <th scope="col">Image(click the image to detail ⬇️)</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>
    <tbody>  
      {% for guide in guide_list %}    
      <tr>
        <th>{{guide[0]}}</th>
        <td>{{guide[1]}}</td>
        <td>{{guide[2]}}</td>
        <td>{{guide[3]}}</td>
        <td>
            <form action="/staff/s_detail" method="get">
              <a href="{{ url_for('staff.s_detail',forestry_id=guide[0])}}"><img class="img-rounded" src="../static/imgdata/{{ guide[4] }}" width=auto height="30px"></a>
            </form>
        </td>
        <td>
          <div class="d-flex">
            <form action="/staff/guide" method="post" id="add_myForm">
                <button type="submit" class="btn btn-success btn-sm me-2" name="add_guide" value="add_guide">Add guide</button>     
            </form>
            <button type="button" class="btn btn-primary btn-sm me-2" onclick="Valuesimg('{{ guide[0] }}')" data-bs-toggle="modal" data-bs-target="#imgmodel">Add img</button>     
            <button type="button" class="btn btn-danger btn-sm me-2" onclick="Valuesdel('{{ guide[0] }}')" data-bs-toggle="modal" data-bs-target="#deletemodel{{ guide[0] }}" >Delete</button>
          </div>   
        </td>      
      </tr>   

      <!-- Modal delete-->
      <div class="modal fade" id="deletemodel{{ guide[0] }}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Delete the guide</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Do you want to delete this guide? When you delete the guide, the detail will also be deleted.
            </div>
            <form class="form-horizontal" style="margin-top: 40px;" action="/staff/index" method="POST" id="myForm_del">
              <input type="hidden" class="form-control" name="delid" id="delid">
            </form>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="submit" class="btn btn-primary" form="myForm_del" name="del_guide" value="del_guide">Delete</button>
            </div>
          </div>
        </div>
      </div>
       <!-- Modal add images-->
       <div class="modal fade" id="imgmodel" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Upload images</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
      
            <div class="modal-body">
              <div class="container-fluid">
                <form class="form-horizontal" style="margin-top: 40px;" action="/staff/index" method="POST" id="img_myForm" enctype="multipart/form-data">
                  <div class="mb-3">
                    <input type="file" class="form-control" name="fileimg" id="fileimg">
                  </div>
                  <input type="hidden" class="form-control" name="forid" id="forid">
                </form>
              </div>
            </div>

            <div class="modal-footer">
              <button type="submit" class="btn btn-primary" form="img_myForm" name="upload" value="upload">Upload</button>
            </div>
          </div>
        </div>
      </div>

      {% endfor %} 
    </tbody>
  </table>
  
  <nav class="pagination-container d-flex justify-content-center" aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item {% if page == 1 %} disabled {% endif %}">
        <a class="page-link" href="?page={{ page-1 }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% for p in range(1, total_pages +1) %}
      <li class="page-item {% if page == p %} active {% endif %}"><a class="page-link" href="?page={{p}}">{{p}}</a></li>
      {% endfor %}
      
      <li class="page-item {% if page == total_pages or total_page == 0 %}disabled {% endif %}">
        <a class="page-link" href="?page={{ page+1 }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
       

<script>
    // get the info when delete
  function Valuesdel(delid) {
    document.getElementById("delid").value = delid;
}

    // get the info when add images
    function Valuesimg(forid) {
    document.getElementById("forid").value = forid;
}
</script>
{% endblock %}

templates/staff/s_base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
  <div class="container-fluid p-3 bg-light text-dark">
    <nav>
        <h1 class="display-5 text-success">Forestry Pest And Disease Biosecurity Guide</h1>
        <ul class="nav">
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('staff.s_index') }}">Guide</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Profile</a>
              <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{{ url_for('staff.s_profile') }}">My Profile</a></li>
              <li><a class="dropdown-item" href="{{ url_for('staff.fprofile') }}">Forester Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{{ url_for('logout') }}">Logout</a></li>
              </ul>
          </li>
        </ul>
    </nav>
  
    
  <section class="content">
    
    <header>
      {% block header %}{% endblock %}
    </header>
    {% for message in get_flashed_messages(with_categories=True) %}
      <div class="alert alert-{{ message[0] }}">
          {{ message[1] }}
      </div>
    {% endfor %}
    {% block content %}{% endblock %}
  
  </section>
</div>

<!-- Bootstrap's JavaScript bundle including Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
(() => {
'use strict'

// Fetch all the forms we want to apply custom Bootstrap validation styles to
const forms = document.querySelectorAll('.needs-validation')

// Loop over them and prevent submission
Array.from(forms).forEach(form => {
  form.addEventListener('submit', event => {
    if (!form.checkValidity()) {
      event.preventDefault()
      event.stopPropagation()
    }

    form.classList.add('was-validated')
  }, false)
})
})()
</script>
</body>

</html>

  