views/forester/__init__.py
from flask import Blueprint

forester_blu = Blueprint("forester",__name__)
from . import views

views/forester/views.py
import base64
import config
import re
from flask import redirect, render_template, request, session, url_for, flash,g
import mysql
import mysql.connector
from . import forester_blu


# connect database
def getCursor():
    global dbconn
    global connection
    connection = mysql.connector.connect(user=config.dbuser, \
    password=config.dbpass, host=config.dbhost, \
    database=config.dbname, autocommit=True,auth_plugin='mysql_native_password')
    dbconn = connection.cursor()
    return dbconn


@forester_blu.route("/index",methods = ["GET","POST"])
def f_index():
    if session['userid'] and session['role'] == "forester" and session['status']== 1:
        connection = getCursor()
        # page setting
        page = request.args.get("page",1,type=int) 
        per_page = 10
        offset = (page -1) * per_page
        connection.execute("""SELECT f.forestry_id,f.forestry_type,
            case when f.present_in_nz = 1 then "yes" when f.present_in_nz=0 then "no" ELSE 'null' END
            ,f.common_name,i.images
            FROM forestry f left join images i
            on f.forestry_id = i.forestry_id
            where i.show_p = 1 order by f.forestry_id limit %s offset %s""",(per_page,offset,))
        guide_list= connection.fetchall()   

        connection.execute("select count(*) from forestry;")
        total = connection.fetchone()[0]   
        total_pages = total // per_page + (1 if total % per_page > 0 else 0)  # calculate the total pages
        
        return render_template("forester/guide.html",guide_list=guide_list,page=page,total_pages=total_pages)

    else:
        return redirect(url_for('login'))
    

@forester_blu.route("/detail")
def f_detail():   
    connection = getCursor()
    if session['userid'] and session['role'] == "forester" and session['status']== 1:
        forestry_id = request.args.get('forestry_id') 
        connection.execute("""SELECT f.forestry_id,f.forestry_type,
            case when f.present_in_nz = 1 then "yes" when f.present_in_nz=0 then "no" ELSE 'null' END
            ,f.common_name,f.scientific_name,f.key_charac,f.biology,f.symptoms,i.images
            FROM forestry f left join images i
            on f.forestry_id = i.forestry_id
            where i.show_p = 1 and f.forestry_id = %s""",(forestry_id,))
        detail_list = connection.fetchall()

        # select all images of the forestry
        connection.execute("""SELECT images FROM images where forestry_id = %s and show_p=0;""",(forestry_id,))
        image_list= connection.fetchall()
        return render_template("/forester/detail.html",detail_list=detail_list,image_list=image_list)
    else:
        return redirect(url_for('login'))
      

@forester_blu.route("/profile",methods = ["GET","POST"])
def f_profile():
    hashing = g.hashing
    connection = getCursor()
    if session['userid'] and session['role'] == "forester" and session['status']== 1:
        # get the profile from database
        user_id = session.get('userid')
        connection.execute("""SELECT * FROM forester where  forester_id= %s;""",(user_id,))
        profile_list= connection.fetchall()

        if request.method == "GET":
            return render_template("/forester/profile.html",profile_list=profile_list)
        else:
            address= request.form.get("address").strip()
            email= request.form.get("email").strip()
            phone= request.form.get("phone").strip()
            password= request.form.get("password").strip()
            password_n= request.form.get("password_n").strip()
            password_c= request.form.get("password_c").strip()

            # modify other info except password
            if re.match(".*@.*",email) and re.match("^\d{1,11}$",phone):
                connection.execute("update forester set address=%s,email=%s,phone=%s where forester_id=%s",(address,email,phone,user_id,)) 
            else:
                flash("Please check the format of email or phone number.","danger")
                return redirect(url_for('forester.f_profile'))    

            # if modify password
            pwd_match = re.match("^(?=.*[a-zA-Z0-9!@#$%^&*()-+=])(?=.*[a-zA-Z0-9]).{8,30}$",password_c)
            if password_n != "" and password_c != "":
                if session['pwd']!= password:    # if the original password is not correct
                    flash("The original password is wrong.","danger")
                    return redirect(url_for('forester.f_profile'))
                else:
                    if password_n != password_c:
                        flash("The second password input is incorrect. Please enter it again.","danger")   
                        return redirect(url_for('forester.f_profile')) 
                    else:
                        if pwd_match: 
                            n_hash = hashing.hash_value(password_c,salt="abc")
                            connection.execute("update forester set pin=%s where forester_id=%s",(n_hash,user_id,))  
                            connection.execute("update users set pin=%s where forester_id=%s",(n_hash,user_id,))
                            flash("Modify profile successfully.","success") 
                            return redirect(url_for('forester.f_profile'))
                        else:
                            flash("Please input your password in right format.","danger")    
                            return redirect(url_for('forester.f_profile')) 
            elif password_n != "" and password_c == "" or password_n == "" and password_c != "":
                flash("Please confirm your password.","danger")    
                return redirect(url_for('forester.f_profile')) 
            elif password != "":
                if session['pwd']!= password:    # if the original password is not correct
                    flash("The original password is wrong.","danger")
                    return redirect(url_for('forester.f_profile'))
            elif password_n != password_c != "" and not re.match("^(?=.*[a-zA-Z0-9!@#$%^&*()-+=])(?=.*[a-zA-Z0-9]).{8,30}$",password_c):
                    flash("Please input your password in right format.","danger")    
                    return redirect(url_for('forester.f_profile')) 
            elif password_n == password_c != "" and not re.match("^(?=.*[a-zA-Z0-9!@#$%^&*()-+=])(?=.*[a-zA-Z0-9]).{8,30}$",password_c):
                    flash("Please input your password in right format.","danger")    
                    return redirect(url_for('forester.f_profile')) 
            
            flash("Modify profile successfully.","success") 
            return redirect(url_for('forester.f_profile'))
        
    else:
        return redirect(url_for('login'))


       

templates/forester/detail.html
{% extends "forester/f_base.html" %}

{% block title %}{{Detail}}{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Type</th>
        <th scope="col">Present in NZ</th>
        <th scope="col">Common Name</th>
        <th scope="col">Scientific name</th>
        <th scope="col">Primary Image</th>
        <th scope="col">Other Images</th>
      </tr>
    </thead>
    <thead>
    </thead>
    <tbody>
      {% for detail in detail_list %}
      <tr>
        <th>{{detail[0]}}</th>
        <td>{{detail[1]}}</td>
        <td>{{detail[2]}}</td>
        <td>{{detail[3]}}</td>
        <td>{{detail[4]}}</td>
        <td>
            <img class="img-rounded" src="../static/imgdata/{{ detail[8] }}"  width=auto height="200px">
        </td>
        <td>
          <div style="height:50px">
            <div class="h-50 d-inline-block" style="width: 200px;">
            <div id="carouselExampleControls" class="carousel slide" data-bs-ride="carousel">
              <div class="carousel-inner ">
                {% for images in image_list %}
                <div class="carousel-item active">
                  <a href=""><img class="mx-auto d-block" width=auto height="200px"src="../static/imgdata/{{ images[0] }}" ></a>
                </div>
                {% endfor %}
              </div>
              <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
              </button>
              <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
              </button>
            </div>
          </div>
          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody> 
  </table>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Key characteristics</th>
        <th scope="col">Biology/Description</th>
        <th scope="col">Symptoms</th>
      </tr>
    </thead>
    <tbody>
      {% for detail in detail_list %}
      <tr>
        <td>{{detail[5]}}</td>
        <td>{{detail[6]}}</td>
        <td>{{detail[7]}}</td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
 
{% endblock %}

templates/forester/f_base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    <!-- Bootstrap CSS link -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
  <div class="container-fluid p-3 bg-light text-dark">
    <nav>
        <h1 class="display-5 text-success">Forestry Pest And Disease Biosecurity Guide</h1>
        <ul class="nav">
          <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{ url_for('forester.f_index') }}">Guide</a>
          </li>
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-expanded="false">Profile</a>
              <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{{ url_for('forester.f_profile') }}">Mangage Profile</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{{ url_for('logout') }}">Logout</a></li>
              </ul>
          </li>
        </ul>
    </nav>
  
    
  <section class="content">
    
    <header>
      {% block header %}{% endblock %}
    </header>
    {% for message in get_flashed_messages(with_categories=True) %}
      <div class="alert alert-{{ message[0] }}">
          {{ message[1] }}
      </div>
    {% endfor %}
    {% block content %}{% endblock %}
  
  </section>
</div>

<!-- Bootstrap's JavaScript bundle including Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
<script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
(() => {
'use strict'

// Fetch all the forms we want to apply custom Bootstrap validation styles to
const forms = document.querySelectorAll('.needs-validation')

// Loop over them and prevent submission
Array.from(forms).forEach(form => {
  form.addEventListener('submit', event => {
    if (!form.checkValidity()) {
      event.preventDefault()
      event.stopPropagation()
    }

    form.classList.add('was-validated')
  }, false)
})
})()
</script>
</body>

</html>

  

templates/forester/guide.html
{% extends "forester/f_base.html" %}

{% block title %}{{Guide}}{% endblock %}

{% block content %}
<table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Type</th>
        <th scope="col">Present in NZ</th>
        <th scope="col">Common Name</th>
        <th scope="col">Image</th>
      </tr>
    </thead>
    <tbody>
      {% for guide in guide_list %}
      <tr>
        <th>{{guide[0]}}</th>
        <td>{{guide[1]}}</td>
        <td>{{guide[2]}}</td>
        <td>{{guide[3]}}</td>
        <td>
            <form action="/foreseter/f_detail" method="get">
              <a href="{{ url_for('forester.f_detail',forestry_id=guide[0])}}"><img class="img-rounded" src="../static/imgdata/{{ guide[4] }}" width=auto height="30px"></a>
            </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

  <nav class="pagination-container d-flex justify-content-center" aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item {% if page == 1 %} disabled {% endif %}">
        <a class="page-link" href="?page={{ page-1 }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% for p in range(1, total_pages +1) %}
      <li class="page-item {% if page == p %} active {% endif %}"><a class="page-link" href="?page={{p}}">{{p}}</a></li>
      {% endfor %}
      
      <li class="page-item {% if page == total_pages or total_page == 0 %}disabled {% endif %}">
        <a class="page-link" href="?page={{ page+1 }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    </ul>
  </nav>
{% endblock %}

templates/forester/profile.html
{% extends "forester/f_base.html" %}

{% block title %}{{Profile}}{% endblock %}

{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">First name</th>
        <th scope="col">Family name</th>
        <th scope="col">Address</th>
        <th scope="col">Email</th>
        <th scope="col">Phone</th>
        <th scope="col">Date Joined</th>
        <th scope="col">Password</th>
      </tr>
    </thead>
    <tbody>
    {% for profile in profile_list %}
      <tr>
        <th scope="row">{{profile[0]}}</th>
        <td>{{profile[2]}}</td>
        <td>{{profile[3]}}</td>
        <td>{{profile[5]}}</td>
        <td>{{profile[6]}}</td>
        <td>{{profile[7]}}</td>
        <td>{{profile[8]}}</td>
        <td>********</td>
        <td>
          <div style="text-align:center">
            <button type="button" class="btn btn-primary" onclick="Values('{{ profile[5] }}','{{ profile[6] }}','{{ profile[7]}}')" data-bs-toggle="modal" data-bs-target="#exampleModal" >Edit</button>
         </div>
        </td>
      </tr>
    {% endfor %}
    </tbody>
  </table>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Edit profile</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
        <div class="container-fluid">
          <form class="form-horizontal needs-validation" style="margin-top: 40px;" action="/forester/profile" method="POST" id="myForm" >
          <div class="mb-3">
            <label for="recipient-name" class="col-form-label">Address</label>
            <input type="text" class="form-control" name="address" id="address" >
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Email</label>
            <input type="email" class="form-control" name="email" id="email">
          </div>    
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Phone</label>
            <input type="tel" maxlength="11" class="form-control" name="phone" id="phone" placeholder="Not exceed 11 digits.">
          </div>
          <div class="mb-3">
            <label for="message-text" class="col-form-label">Original password</label>
            <input type="password" class="form-control" name="password" id="password" placeholder="If you want to change your password, please input your original password.">
          </div>
          <div class="row">
          <div class="col-md-6 mb-3">
            <label for="message-text" class="col-form-label">New password</label>
            <input type="password" class="form-control" name="password_n" id="password_n">
          </div>
          <div class="col-md-6 mb-3">
            <label for="message-text" class="col-form-label">Confirm new password</label>
            <input type="password" class="form-control" name="password_c" id="password_c">
          </div>
          </div>
        </form>
        </div>
      </div>


      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" form="myForm" >Save changes</button>
      </div>
    </div>
  </div>
</div>


<script>
  function Values(address, email, phone) {
    document.getElementById("address").value = address;
    document.getElementById("email").value = email;
    document.getElementById("phone").value = phone;
  }
</script>

{% endblock %}